# 1. Cấu hình kết nối cơ sở dữ liệu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/pfma_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=26112006Cuong.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Cấu hình Hibernate JPA tự động đồng bộ thực thể sang MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Cấu hình Spring Mail (Luồng quên mật khẩu vừa làm)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Điền Gmail và App Password của bạn vào đây
spring.mail.username=nobijust1@gmail.com
spring.mail.password=xbjrwldvawebyinn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Ép Jackson tự bỏ qua các thực thể Lazy Loading rỗng thay vì bùng lỗi ByteBuddy
spring.jackson.serialization.fail-on-empty-beans=false